"""
Create test client record in Supabase for 'agentic-dev' tenant.

This script creates the client record that the Persistence Agent needs
for FK constraints. The client_uuid is deterministically generated from
the tenant_id 'agentic-dev' using UUID5.

Run once: python -m scripts.create_test_client
"""

import os
import sys
import uuid
from dotenv import load_dotenv

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services.persistence.adapters.supabase_adapter import SupabaseAdapter

# Load environment
load_dotenv()

# Generate the same UUID the agent uses
TENANT_ID = "agentic-dev"
CLIENT_UUID = str(uuid.uuid5(uuid.NAMESPACE_DNS, TENANT_ID))

print(f"Creating test client for tenant: {TENANT_ID}")
print(f"Client UUID: {CLIENT_UUID}")

# Initialize Supabase
supabase_url = os.environ.get("SUPABASE_URL")
supabase_key = os.environ.get("SUPABASE_SERVICE_KEY") or os.environ.get("SUPABASE_KEY")

if not supabase_url or not supabase_key:
    print("ERROR: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in .env")
    exit(1)

supabase = SupabaseAdapter(supabase_url, supabase_key)

# Create client record
client_record = {
    "id": CLIENT_UUID,
    "name": "Agentic Dev Test Client"
    # created_at and updated_at are auto-generated by Supabase
}

try:
    result = supabase.write(table="clients", record=client_record)
    print(f"\n✅ SUCCESS: Test client created!")
    print(f"   ID: {CLIENT_UUID}")
    print(f"   Name: {client_record['name']}")
    print(f"\nYou can now run Persistence Agent tests.")
except Exception as e:
    if "duplicate key" in str(e).lower() or "already exists" in str(e).lower():
        print(f"\n✓ Client already exists (ID: {CLIENT_UUID})")
        print("No action needed - tests can proceed.")
    else:
        print(f"\n❌ ERROR: {e}")
        print("\nPlease check:")
        print("  1. Supabase credentials in .env")
        print("  2. 'clients' table exists in Supabase")
        print("  3. Required fields in clients table schema")
