apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentic-worker
  namespace: {{ include "agentic.namespace" . }}
  annotations:
    {{- if eq .Values.secrets.provider "aws" }}
    eks.amazonaws.com/role-arn: ""
    {{- end }}
    {{- if eq .Values.secrets.provider "azure" }}
    azure.workload.identity/client-id: "{{ .Values.secrets.azure.clientId }}"
    {{- end }}
  labels:
    {{- if eq .Values.secrets.provider "azure" }}
    azure.workload.identity/use: "true"
    {{- end }}
